#!groovy

// Requires docker-workflow plugin
// https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Pipeline+Plugin

node {
  checkout scm
  def workspace = pwd()

  stage('Build') {
    docker.image('gcc:6.3').inside("-v ${workspace}:/build") {
      sh 'make'
    }
  }

  stage('Test') {
    docker.image('robotframework:latest').inside("-v ${workspace}:/build") {
      sh 'make test'
    }
  }
}
